package data.datasource.local

import data.models.BookModel

/**
 * Singleton For LocalDataSource
 * @property bookList [MutableList]<[BookModel]>, The on-memory data store for books
 */
object LocalDataSource {
    private val bookList: MutableList<BookModel> = mutableListOf()

    /**
     * To add new book to LocalDataSource
     * @param bookName, [String] the name of the book
     * @param authorName, [String] the name of the author
     * @param publishYear, [Int] the year of the book published
     */
    fun add(
        bookName: String,
        authorName: String,
        publishYear: Int
    ) {
        bookList.add(
            BookModel(
                bookName = bookName,
                authorName = authorName,
                publishYear = publishYear,
                bookId = autoGeneratedId()
            )
        )
    }

    /**
     * To retrieve all books from LocalDataSource
     * @return [List]<[BookModel]>
     */
    fun getAll(): List<BookModel> {
        return bookList
    }

    /**
     * To generate unique id for the book.
     * @return [Int], the auto generated id of the book
     */
    private fun autoGeneratedId(): Int {
        return bookList.lastOrNull()?.let { it.bookId + 1 } ?: 1
    }
}