package controllers

import models.BookModel

/**
 * Controller class for book store. It supports add books and display books.
 * @property bookList, [MutableList] <[BookModel]>
 */
class BookStoreController {
    private val bookList: MutableList<BookModel> = mutableListOf()

    /**
     * To add the book the book list.
     * @param bookName, [String] the name of the book
     * @param authorName, [String] the name of the author
     * @param publishYear, [Int] the year of the book published
     */
    fun addBook(
        bookName: String,
        authorName: String,
        publishYear: Int
    ) {
        bookList.add(
            BookModel(
                bookName = bookName,
                authorName = authorName,
                publishYear = publishYear,
                bookId = autoGeneratedId()
            )
        )
    }

    /**
     * To generate unique id for the book.
     * @return [Int], the auto generated id of the book
     */
    private fun autoGeneratedId(): Int {
        return bookList.lastOrNull()?.let { it.bookId+1 } ?: 1
    }

    /**
     * To display books from book list.
     */
    fun displayBook() {
        if (bookList.isEmpty()) {
            println("There is no book.")
        } else {
            bookList.forEach{
                println(it)
            }
        }
    }
}